fsh/models/__init__.py
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

fsh/models/models.py
from . import db


# class Category(db.Model):
#     id = db.Column(db.Integer, primary_key=True)
#     name = db.Column(db.String(80), nullable=False, unique=True)
#
#     products = db.relationship('Product', back_populates='category')


class Product(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(80), nullable=False)
    description = db.Column(db.String(240))
    weight = db.Column(db.Integer, nullable=False)
    image = db.Column(db.String(80))

    taken = db.Column(db.Boolean, default=False)

    # category_id = db.Column(db.Integer, db.ForeignKey('category.id'))
    # category = db.relationship('Category', back_populates='products')

fsh/blueprints/api.py
import uuid
import os
from flask import Blueprint, jsonify, request, render_template, redirect, url_for, send_from_directory
from flask import current_app as app

import fsh.models.models as models

bp = Blueprint('api', __name__)


def allowed_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in app.config['ALLOWED_EXTENSIONS']


@bp.route("/")
def index():
    return render_template('landing.html')


@bp.route("/add", methods=["GET"])
def add():
    products = models.Product.query.all()
    return render_template('add.html', products=products)


@bp.route("/add", methods=["POST"])
def add_post():
    name = request.form['product']
    weight = request.form['weight']
    if weight.endswith("g"):
        weight = weight[:-1]
    weight = int(weight)
    description = request.form['description']
    entry = models.Product(name=name, weight=weight, description=description)

    if 'image' in request.files:
        file = request.files['image']
        if file.filename != "" and allowed_file(file.filename):
            filename = str(uuid.uuid4()) + "." + file.filename.rsplit('.', 1)[1].lower()
            file.save(os.path.join(app.config['UPLOAD_FOLDER'], filename))
            entry.image = filename

    models.db.session.add(entry)
    models.db.session.commit()
    return redirect(url_for('api.index'))
    # e = models.ProductEntry()


@bp.route("/take", methods=["GET"])
def take():
    entries = models.Product.query.filter_by(taken=False)
    return render_template('take.html', entries=entries)


@bp.route("/take/<id>", methods=["POST"])
def take_post(id):
    entry = models.Product.query.get(id)

    if request.form['weight'] == '':
        weight_taken = None
    else:
        weight_taken = int(request.form['weight'])

    old_weight = entry.weight
    if weight_taken is None or weight_taken >= old_weight - 10:
        entry.taken = True
    else:
        entry.weight = old_weight - weight_taken

    models.db.session.add(entry)
    models.db.session.commit()
    return redirect(url_for('api.take'))


@bp.route("/image/<path:filename>")
def image(filename):
    return send_from_directory(app.config['UPLOAD_FOLDER'], filename)

fsh/templates/add.html
{% extends "base.html" %}
{% block body %}
<div class="container">
  <form action="{{ url_for('api.add_post') }}" method="post" enctype=multipart/form-data>
    <div class="form-group row">
      <label for="product" class="col-sm-2 col-form-label">Produkt</label>
      <div class="col-sm-10">
        <input class="form-control" id="product" name="product"></input>
      </div>
      <label for="description" class="col-sm-2 col-form-label">Beschreibung</label>
      <div class="col-sm-10">
        <input class="form-control" id="description" name="description" placeholder="z.B. Wo ist's übrig geblieben?"></input>
      </div>
      <label for="weight" class="col-sm-2 col-form-label">Gewicht</label>
      <div class="col-sm-10">
        <input class="form-control" id="weight" placeholder="100g" name="weight"></input>
      </div>
      <label for="image" class="col-sm-2 col-form-label">Foto</label>
      <div class="col-sm-10">
        <input type="file" name="image"></input>
      </div>

      <div class="buttons">
        <a href="{{ url_for('api.index') }}" class="btn btn-warning">Abbrechen</a>
        <button type="submit" class="btn btn-primary">Speichern</button>
      </div>
    </div>
  </form>
</div>
{% endblock %}

fsh/templates/base.html
<!DOCTYPE html>
<head>
  <title>{% block title%}fsh – foodsharinghub{% endblock %}</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="{{ url_for('static', filename='dist/css/bootstrap.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
</head>

<body>
  <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
      <a class="navbar-brand" href="/">foodsharinghub</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li {% if request.path == '/add' %}class="nav-item active"{% else %} class="nav-item" {% endif %}>
            <a class="nav-link" href="/add">Hinzufügen</a>
          </li>
          <li {% if request.path == '/take' %}class="nav-item active"{% else %} class="nav-item" {% endif %}>
            <a class="nav-link" href="/take">Entnehmen</a>
          </li>
        </ul>
      </div>
    </nav>
  {% block body %} {% endblock %}

  <script src="{{ url_for('static', filename='jquery-3.2.1.min.js') }}"></script>
  <script src="{{ url_for('static', filename='dist/js/bootstrap.js') }}"></script>
</body>

fsh/templates/landing.html
{% extends "base.html" %}
{% block body %}
<div class="container" id="landing">
  <div>
    <a href="{{ url_for('api.add') }}" type="button" class="btn btn-primary btn-block">Lebensmittel hinzufügen &gt;</a>
  </div>
  <div>
    <a href="{{ url_for('api.take') }}" type="button" class="btn btn-primary btn-block">Lebensmittel entnehmen &gt;</a>
  </div>
</div>
{% endblock %}

fsh/templates/take.html
{% extends "base.html" %}
{% block body %}
<div class="container">
  <div class="row">
    {% for entry in entries %}
    <div class="entry col-sm-4">
      <h2>{{ entry.name }}</h2>
      {% if entry.image is not none %}
      <img class="preview" src="{{ url_for('api.image', filename=entry.image) }}"></img>
      {% endif %}
      {% if entry.description %}
      <p>{{ entry.description }}</p>
      {% endif %}
      <p>noch <b>{{ entry.weight }}g</b> übrig</p>
      <form action="{{ url_for('api.take') }}/{{ entry.id }}" method="post">
        <div class="form-group row">
          <div class="col-4">
            <input class="form-control" id="weight" name="weight" placeholder="Gewicht"></input>
          </div>
          <button class="col-7 btn btn-primary btn-block" type="submit" name="{{ entry.id }}">Nehmen</button>
        </div>
      </form>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}